### ISSUE TITLE
Text is getting cut in narrow windows

### ISSUE THREAD

**Issue by ceilican** [DjedAlliance/DjedAlliance.github.io#10]
<img width="309" alt="Screenshot 2024-12-03 at 09 07 36" src="https://github.com/user-attachments/assets/400836cf-495d-49e7-94f0-b41895c7f54c">
<img width="292" alt="Screenshot 2024-12-03 at 09 07 41" src="https://github.com/user-attachments/assets/25c5f26c-9b13-4bef-88fd-0ecdd27324c1">

**Comment by CHIRANTH-24** [comment]
@ceilican I would like to work on this

**Comment by CHIRANTH-24** [comment]
![image](https://github.com/user-attachments/assets/79cac43e-a032-40bd-9290-daaf8534c122)
![image](https://github.com/user-attachments/assets/461fb995-0034-4453-87d6-694c02f2e95b)
