### ISSUE TITLE
Automate deployment with Github Actions

### ISSUE THREAD

**Issue by ceilican** [DjedAlliance/DjedAlliance.github.io#12]
Currently, this website requires manual deployment to github pages using the instructions in the Readme.md file. We would like to automate this process using github actions, so that the deploying happens whenever we push new commits to the main branch.

**Comment by pavanydg** [comment]
@ceilican i would like to work on this. Please assign me

**Comment by notmanjit** [comment]
@ceilican I tried to fix the issue. Please review my request
