### ISSUE TITLE
https://djed.one not displayed correctly on Mobile

### ISSUE THREAD

**Issue by ceilican** [DjedAlliance/DjedAlliance.github.io#9]
Some sections of https://djed.one are not displayed correctly on mobile. Fix these sections.

**Comment by CHIRANTH-24** [comment]
@ceilican May I work on this issue?

**Comment by CHIRANTH-24** [comment]
When I run npm run dev, the issue seems to be fixed!

When I tried npm run deploy, I am denied of access.

How do I reproduce this issue?

**Comment by SHOBHIT112005** [comment]
@CHIRANTH-24 is right and I think during deployment of the website few CSS classes are not correctly applied, I also want to wok on this please @ceilican

**Comment by ceilican** [comment]
![WhatsApp Image 2024-12-02 at 09 35 41](https://github.com/user-attachments/assets/b5852b77-9e6d-42e3-bf9c-919c889901c1)

**Comment by ceilican** [comment]
As you can see above, the issue is not related to css classes not being applied. It is simply a matter of cards becoming squeezed due to the the fact that a mobile's screen is narrow.

I think the easiest way of solving this is by using a carrousel, as is done in the "The Alliance's Contributor's" section below.

**Comment by ceilican** [comment]
![WhatsApp Image 2024-12-02 at 09 40 18](https://github.com/user-attachments/assets/fef05240-6ace-4f38-bd84-8c8a0ea21f9c)

**Comment by SHOBHIT112005** [comment]
![Screenshot 2024-12-02 122041](https://github.com/user-attachments/assets/e374177a-a864-41e4-bf25-0d3c67d90c92)
As you can see, when we perform npm run dev, and run it on localhost, then we can see a similar carrousel for the cards and they appear correctly.

**Comment by ceilican** [comment]
@SHOBHIT112005 , I couldn't find you in our discord. Could you join here (https://discord.gg/YzDKeEfWtS) and then send me (@Bruno) a message there?

**Comment by CHIRANTH-24** [comment]
@ceilican Can this issue be closed?

**Comment by ceilican** [comment]
Thanks, @CHIRANTH-24 .
